// 课程清单：数据即代码（file:// 下 fetch json 会被 CORS 拦截，故用 script 加载）。
// 新增一课：在对应章节 lessons 里登记 {id,title,path,status,scenes,expectSteps}，
// status: 'done' 的课会被 tests/courses.test.js 校验场景结构。
window.COURSES = {
  updated: '2026-07-14',
  stages: [
    {
      id: 'junior', title: '初中',
      books: [
        { id: 'grade7a', title: '七年级上册', chapters: [
          { id: 'ch01', title: '第1章 有理数', lessons: [] },
          { id: 'ch02', title: '第2章 整式的加减', lessons: [] },
          { id: 'ch03', title: '第3章 一元一次方程', lessons: [
            {
              id: '7a-3.1',
              title: '3.1 一元一次方程（概念与等式性质）',
              path: 'courses/junior/grade7a/ch03-linear-equations/s3.1-concept-and-properties/',
              status: 'done',
              scenes: ['s1-intro.js', 's2-what.js', 's3-linear.js', 's4-balance.js',
                's5-examples.js', 's6-transposition.js', 's7-summary.js'],
              expectSteps: [3, 3, 4, 5, 4, 3, 6],
            },
          ] },
          { id: 'ch04', title: '第4章 几何图形初步', lessons: [] },
        ] },
        { id: 'grade7b', title: '七年级下册', chapters: [
          { id: 'ch05', title: '第5章 相交线与平行线', lessons: [
            {
              id: '7b-5.1',
              title: '5.1 相交线、邻补角与对顶角',
              path: 'courses/junior/grade7b/ch05-intersecting-parallel-lines/t01-intersecting-lines/',
              status: 'done',
              scenes: ['s1-intro.js', 's2-crossing.js', 's3-adjacent.js', 's4-vertical.js',
                's5-example.js', 's6-summary.js'],
              expectSteps: [3, 4, 4, 4, 3, 3],
            },
            {
              id: '7b-5.2',
              title: '5.2 垂线与垂线段',
              path: 'courses/junior/grade7b/ch05-intersecting-parallel-lines/t02-perpendicular/',
              status: 'done',
              scenes: ['s1-intro.js', 's2-definition.js', 's3-uniqueness.js', 's4-shortest.js',
                's5-distance.js', 's6-summary.js'],
              expectSteps: [2, 4, 4, 4, 3, 2],
            },
            {
              id: '7b-5.3',
              title: '5.3 观察与猜想：看图时的错觉',
              path: 'courses/junior/grade7b/ch05-intersecting-parallel-lines/t03-visual-illusion/',
              status: 'done',
              scenes: ['s1-intro.js', 's2-segments.js', 's3-parallel.js', 's4-circles.js',
                's5-summary.js'],
              expectSteps: [2, 4, 4, 4, 3],
            },
            {
              id: '7b-5.4',
              title: '5.4 平行线及其基本事实',
              path: 'courses/junior/grade7b/ch05-intersecting-parallel-lines/t04-parallel-basics/',
              status: 'done',
              scenes: ['s1-intro.js', 's2-definition.js', 's3-axiom.js', 's4-corollary.js',
                's5-summary.js'],
              expectSteps: [2, 4, 4, 3, 3],
            },
            {
              id: '7b-5.5',
              title: '5.5 平行线的判定',
              path: 'courses/junior/grade7b/ch05-intersecting-parallel-lines/t05-parallel-judgment/',
              status: 'done',
              scenes: ['s1-eight-angles.js', 's2-corresponding.js', 's3-alternate.js',
                's4-cointerior.js', 's5-judgments.js', 's6-example.js', 's7-summary.js'],
              expectSteps: [3, 3, 3, 3, 5, 2, 3],
            },
            {
              id: '7b-5.6',
              title: '5.6 平行线的性质',
              path: 'courses/junior/grade7b/ch05-intersecting-parallel-lines/t06-parallel-properties/',
              status: 'done',
              scenes: ['s1-intro.js', 's2-property1.js', 's3-property2.js', 's4-property3.js',
                's5-example.js', 's6-summary.js'],
              expectSteps: [3, 4, 3, 3, 3, 3],
            },
            {
              id: '7b-5.7',
              title: '5.7 判定与性质的综合应用',
              path: 'courses/junior/grade7b/ch05-intersecting-parallel-lines/t07-comprehensive/',
              status: 'done',
              scenes: ['s1-contrast.js', 's2-method.js', 's3-chain.js', 's4-format.js',
                's5-exit.js'],
              expectSteps: [3, 3, 5, 3, 4],
            },
            {
              id: '7b-5.8',
              title: '5.8 定义、命题、定理',
              path: 'courses/junior/grade7b/ch05-intersecting-parallel-lines/t08-propositions/',
              status: 'done',
              scenes: ['s1-definition.js', 's2-proposition.js', 's3-structure.js',
                's4-truefalse.js', 's5-theorem.js'],
              expectSteps: [3, 4, 4, 4, 3],
            },
            {
              id: '7b-5.9',
              title: '5.9 平移及其性质',
              path: 'courses/junior/grade7b/ch05-intersecting-parallel-lines/t09-translation/',
              status: 'done',
              scenes: ['s1-intro.js', 's2-definition.js', 's3-properties.js', 's4-drawing.js',
                's5-example.js', 's6-summary.js'],
              expectSteps: [2, 3, 5, 4, 3, 2],
            },
            {
              id: '7b-5.10',
              title: '5.10 利用平移设计图案',
              path: 'courses/junior/grade7b/ch05-intersecting-parallel-lines/t10-pattern-design/',
              status: 'done',
              scenes: ['s1-observe.js', 's2-find.js', 's3-design.js', 's4-task.js'],
              expectSteps: [3, 4, 5, 3],
            },
            {
              id: '7b-5.11',
              title: '5.11 单元小结与复习',
              path: 'courses/junior/grade7b/ch05-intersecting-parallel-lines/t11-review/',
              status: 'done',
              scenes: ['s1-network.js', 's2-intersect.js', 's3-parallel.js', 's4-prop-trans.js',
                's5-eight.js'],
              expectSteps: [3, 3, 4, 3, 3],
            },
          ] },
          { id: 'ch06', title: '第6章 实数', lessons: [
            {
              id: '7b-6.1',
              title: '6.1 平方根与开平方',
              path: 'courses/junior/grade7b/ch06-real-numbers/t01-square-root/',
              status: 'done',
              scenes: ['s1-intro.js', 's2-definition.js', 's3-cases.js', 's4-operation.js',
                's5-examples.js', 's6-summary.js'],
              expectSteps: [3, 4, 4, 3, 4, 3],
            },
            {
              id: '7b-6.2',
              title: '6.2 算术平方根',
              path: 'courses/junior/grade7b/ch06-real-numbers/t02-arithmetic-sqrt/',
              status: 'done',
              scenes: ['s1-review.js', 's2-definition.js', 's3-nonneg.js', 's4-examples.js',
                's5-summary.js'],
              expectSteps: [3, 4, 3, 3, 3],
            },
            {
              id: '7b-6.3',
              title: '6.3 平方根的估算与应用',
              path: 'courses/junior/grade7b/ch06-real-numbers/t03-estimation/',
              status: 'done',
              scenes: ['s1-intro.js', 's2-squeeze.js', 's3-approx.js', 's4-apply.js',
                's5-summary.js'],
              expectSteps: [2, 5, 3, 3, 2],
            },
            {
              id: '7b-6.4',
              title: '6.4 立方根',
              path: 'courses/junior/grade7b/ch06-real-numbers/t04-cube-root/',
              status: 'done',
              scenes: ['s1-intro.js', 's2-definition.js', 's3-negative.js', 's4-examples.js',
                's5-summary.js'],
              expectSteps: [2, 4, 3, 3, 3],
            },
            {
              id: '7b-6.5',
              title: '6.5 无理数与实数',
              path: 'courses/junior/grade7b/ch06-real-numbers/t05-irrational/',
              status: 'done',
              scenes: ['s1-what.js', 's2-definition.js', 's3-tree.js', 's4-sorting.js',
                's5-summary.js'],
              expectSteps: [3, 3, 4, 6, 2],
            },
            {
              id: '7b-6.6',
              title: '6.6 实数与数轴、大小比较',
              path: 'courses/junior/grade7b/ch06-real-numbers/t06-number-line/',
              status: 'done',
              scenes: ['s1-question.js', 's2-locate.js', 's3-correspond.js', 's4-compare.js',
                's5-summary.js'],
              expectSteps: [2, 5, 3, 4, 2],
            },
            {
              id: '7b-6.7',
              title: '6.7 实数的运算',
              path: 'courses/junior/grade7b/ch06-real-numbers/t07-operations/',
              status: 'done',
              scenes: ['s1-rules.js', 's2-combine.js', 's3-absolute.js', 's4-mixed.js',
                's5-summary.js'],
              expectSteps: [3, 4, 3, 4, 2],
            },
            {
              id: '7b-6.8',
              title: '6.8 为什么 √2 不是有理数',
              path: 'courses/junior/grade7b/ch06-real-numbers/t08-proof/',
              status: 'done',
              scenes: ['s1-question.js', 's2-method.js', 's3-proof.js', 's4-history.js',
                's5-summary.js'],
              expectSteps: [3, 3, 5, 3, 2],
            },
            {
              id: '7b-6.9',
              title: '6.9 数学活动与单元复习',
              path: 'courses/junior/grade7b/ch06-real-numbers/t09-review/',
              status: 'done',
              scenes: ['s1-network.js', 's2-roots.js', 's3-real.js', 's4-errors.js',
                's5-exit.js'],
              expectSteps: [3, 3, 3, 3, 3],
            },
          ] },
          { id: 'ch07', title: '第7章 平面直角坐标系', lessons: [
            {
              id: '7b-7.1',
              title: '7.1 有序数对与位置表示',
              path: 'courses/junior/grade7b/ch07-coordinate-system/t01-ordered-pair/',
              status: 'done',
              scenes: ['s1-intro.js', 's2-ordered.js', 's3-notation.js', 's4-practice.js',
                's5-summary.js'],
              expectSteps: [3, 3, 3, 3, 2],
            },
            {
              id: '7b-7.2',
              title: '7.2 平面直角坐标系',
              path: 'courses/junior/grade7b/ch07-coordinate-system/t02-plane-system/',
              status: 'done',
              scenes: ['s1-build.js', 's2-elements.js', 's3-quadrants.js', 's4-identify.js',
                's5-summary.js'],
              expectSteps: [3, 4, 5, 3, 2],
            },
            {
              id: '7b-7.3',
              title: '7.3 点的坐标与描点',
              path: 'courses/junior/grade7b/ch07-coordinate-system/t03-point-coordinate/',
              status: 'done',
              scenes: ['s1-read.js', 's2-plot.js', 's3-meaning.js', 's4-practice.js',
                's5-summary.js'],
              expectSteps: [3, 3, 3, 3, 2],
            },
            {
              id: '7b-7.4',
              title: '7.4 各象限及坐标轴上点的特征',
              path: 'courses/junior/grade7b/ch07-coordinate-system/t04-quadrant-signs/',
              status: 'done',
              scenes: ['s1-intro.js', 's2-signs.js', 's3-axis.js', 's4-apply.js',
                's5-summary.js'],
              expectSteps: [2, 5, 4, 2, 2],
            },
            {
              id: '7b-7.5',
              title: '7.5 用坐标表示图形和地点的位置',
              path: 'courses/junior/grade7b/ch07-coordinate-system/t05-describe-position/',
              status: 'done',
              scenes: ['s1-place.js', 's2-choose-origin.js', 's3-shape.js', 's4-apply.js',
                's5-summary.js'],
              expectSteps: [3, 3, 4, 3, 2],
            },
            {
              id: '7b-7.6',
              title: '7.6 坐标与平移',
              path: 'courses/junior/grade7b/ch07-coordinate-system/t06-translation/',
              status: 'done',
              scenes: ['s1-point.js', 's2-rule.js', 's3-shape.js', 's4-inverse.js',
                's5-summary.js'],
              expectSteps: [3, 3, 4, 3, 2],
            },
            {
              id: '7b-7.7',
              title: '7.7 坐标方法的简单应用',
              path: 'courses/junior/grade7b/ch07-coordinate-system/t07-application/',
              status: 'done',
              scenes: ['s1-route.js', 's2-build-system.js', 's3-distance.js', 's4-comprehensive.js',
                's5-summary.js'],
              expectSteps: [3, 3, 3, 3, 2],
            },
            {
              id: '7b-7.8',
              title: '7.8 用经纬度表示地理位置',
              path: 'courses/junior/grade7b/ch07-coordinate-system/t08-longitude-latitude/',
              status: 'done',
              scenes: ['s1-intro.js', 's2-lines.js', 's3-coordinate.js', 's4-analogy.js',
                's5-summary.js'],
              expectSteps: [3, 4, 4, 3, 2],
            },
            {
              id: '7b-7.9',
              title: '7.9 数学活动与单元复习',
              path: 'courses/junior/grade7b/ch07-coordinate-system/t09-review/',
              status: 'done',
              scenes: ['s1-network.js', 's2-quadrant.js', 's3-plot-shape.js', 's4-translation.js',
                's5-exit.js'],
              expectSteps: [3, 3, 3, 3, 3],
            },
          ] },
          { id: 'ch08', title: '第8章 二元一次方程组', lessons: [
            {
              id: '7b-8.1',
              title: '8.1 二元一次方程',
              path: 'courses/junior/grade7b/ch08-linear-systems/t01-two-var-equation/',
              status: 'done',
              scenes: ['s1-intro.js', 's2-definition.js', 's3-solutions.js', 's4-express.js',
                's5-summary.js'],
              expectSteps: [3, 3, 4, 3, 2],
            },
            {
              id: '7b-8.2',
              title: '8.2 二元一次方程组及其解',
              path: 'courses/junior/grade7b/ch08-linear-systems/t02-system-and-solution/',
              status: 'done',
              scenes: ['s1-system.js', 's2-solution.js', 's3-intersection.js', 's4-practice.js',
                's5-summary.js'],
              expectSteps: [3, 4, 4, 3, 2],
            },
            {
              id: '7b-8.3',
              title: '8.3 代入消元法',
              path: 'courses/junior/grade7b/ch08-linear-systems/t03-substitution/',
              status: 'done',
              scenes: ['s1-idea.js', 's2-steps.js', 's3-format.js', 's4-check.js',
                's5-summary.js'],
              expectSteps: [3, 5, 3, 3, 2],
            },
            {
              id: '7b-8.4',
              title: '8.4 代入法综合应用',
              path: 'courses/junior/grade7b/ch08-linear-systems/t04-substitution-advanced/',
              status: 'done',
              scenes: ['s1-review.js', 's2-transform.js', 's3-fraction.js', 's4-holistic.js',
                's5-summary.js'],
              expectSteps: [2, 4, 3, 3, 2],
            },
          ] },
          { id: 'ch09', title: '第9章 不等式与不等式组', lessons: [] },
          { id: 'ch10', title: '第10章 数据的收集、整理与描述', lessons: [
            {
              id: '7b-10.1',
              title: '10.1 统计调查与调查方式',
              path: 'courses/junior/grade7b/ch10-data-collection/t01-survey-methods/',
              status: 'done',
              scenes: ['s1-intro.js', 's2-census.js', 's3-sampling.js', 's4-choose.js',
                's5-summary.js'],
              expectSteps: [2, 3, 3, 4, 2],
            },
            {
              id: '7b-10.2',
              title: '10.2 总体、个体、样本与样本容量',
              path: 'courses/junior/grade7b/ch10-data-collection/t02-population-sample/',
              status: 'done',
              scenes: ['s1-intro.js', 's2-population.js', 's3-sample.js', 's4-practice.js',
                's5-summary.js'],
              expectSteps: [2, 3, 4, 4, 2],
            },
            {
              id: '7b-10.3',
              title: '10.3 调查问卷设计与数据收集',
              path: 'courses/junior/grade7b/ch10-data-collection/t03-questionnaire/',
              status: 'done',
              scenes: ['s1-sources.js', 's2-structure.js', 's3-principles.js', 's4-tally.js',
                's5-summary.js'],
              expectSteps: [2, 3, 4, 3, 2],
            },
            {
              id: '7b-10.4',
              title: '10.4 探究：瓶子中有多少粒豆子',
              path: 'courses/junior/grade7b/ch10-data-collection/t04-beans-estimation/',
              status: 'done',
              scenes: ['s1-problem.js', 's2-method.js', 's3-idea.js', 's4-variation.js',
                's5-summary.js'],
              expectSteps: [2, 5, 3, 3, 2],
            },
            {
              id: '7b-10.5',
              title: '10.5 用统计表和条形统计图描述数据',
              path: 'courses/junior/grade7b/ch10-data-collection/t05-bar-chart/',
              status: 'done',
              scenes: ['s1-table.js', 's2-bar.js', 's3-read.js', 's4-steps.js',
                's5-summary.js'],
              expectSteps: [3, 4, 3, 3, 2],
            },
            {
              id: '7b-10.6',
              title: '10.6 扇形统计图与折线统计图',
              path: 'courses/junior/grade7b/ch10-data-collection/t06-pie-line-chart/',
              status: 'done',
              scenes: ['s1-pie.js', 's2-angle.js', 's3-line.js', 's4-choose.js',
                's5-comprehensive.js', 's6-summary.js'],
              expectSteps: [4, 3, 4, 3, 2, 2],
            },
            {
              id: '7b-10.7',
              title: '10.7 频数分布表与频数分布图',
              path: 'courses/junior/grade7b/ch10-data-collection/t07-frequency-distribution/',
              status: 'done',
              scenes: ['s1-why.js', 's2-grouping.js', 's3-histogram.js', 's4-read.js',
                's5-summary.js'],
              expectSteps: [3, 4, 4, 3, 2],
            },
            {
              id: '7b-10.8',
              title: '10.8 利用信息技术工具画统计图',
              path: 'courses/junior/grade7b/ch10-data-collection/t08-tech-tools/',
              status: 'done',
              scenes: ['s1-manual-vs-tech.js', 's2-spreadsheet.js', 's3-generate.js', 's4-tips.js',
                's5-summary.js'],
              expectSteps: [2, 3, 4, 3, 2],
            },
            {
              id: '7b-10.9',
              title: '10.9 数学活动与统计图辨析',
              path: 'courses/junior/grade7b/ch10-data-collection/t09-chart-analysis/',
              status: 'done',
              scenes: ['s1-intro.js', 's2-axis-zero.js', 's3-width-3d.js', 's4-line-scale.js',
                's5-summary.js'],
              expectSteps: [2, 4, 3, 4, 3],
            },
            {
              id: '7b-10.10',
              title: '10.10 综合与实践：白昼时长规律的探究',
              path: 'courses/junior/grade7b/ch10-data-collection/t10-daylight-project/',
              status: 'done',
              scenes: ['s1-intro.js', 's2-collect.js', 's3-line-chart.js', 's4-analyze.js',
                's5-summary.js'],
              expectSteps: [2, 3, 4, 3, 3],
            },
          ] },
        ] },
        { id: 'grade8a', title: '八年级上册', chapters: [
          { id: 'ch11', title: '第11章 三角形', lessons: [] },
          { id: 'ch12', title: '第12章 全等三角形', lessons: [] },
          { id: 'ch13', title: '第13章 轴对称', lessons: [] },
          { id: 'ch14', title: '第14章 整式的乘法与因式分解', lessons: [] },
          { id: 'ch15', title: '第15章 分式', lessons: [] },
        ] },
        { id: 'grade8b', title: '八年级下册', chapters: [
          { id: 'ch16', title: '第16章 二次根式', lessons: [] },
          { id: 'ch17', title: '第17章 勾股定理', lessons: [] },
          { id: 'ch18', title: '第18章 平行四边形', lessons: [] },
          { id: 'ch19', title: '第19章 一次函数', lessons: [] },
          { id: 'ch20', title: '第20章 数据的分析', lessons: [] },
        ] },
        { id: 'grade9a', title: '九年级上册', chapters: [
          { id: 'ch21', title: '第21章 一元二次方程', lessons: [] },
          { id: 'ch22', title: '第22章 二次函数', lessons: [] },
          { id: 'ch23', title: '第23章 旋转', lessons: [] },
          { id: 'ch24', title: '第24章 圆', lessons: [] },
          { id: 'ch25', title: '第25章 概率初步', lessons: [] },
        ] },
        { id: 'grade9b', title: '九年级下册', chapters: [
          { id: 'ch26', title: '第26章 反比例函数', lessons: [] },
          { id: 'ch27', title: '第27章 相似', lessons: [] },
          { id: 'ch28', title: '第28章 锐角三角函数', lessons: [] },
          { id: 'ch29', title: '第29章 投影与视图', lessons: [] },
        ] },
        { id: 'bridge', title: '初高中衔接', chapters: [
          { id: 'ch01', title: '集合初步', lessons: [
            {
              id: 'bridge-1.1',
              title: '集合的交集',
              path: 'courses/junior/bridge/ch01-sets/s1-intersection/',
              status: 'done',
              scenes: ['s1-intro.js', 's2-observe.js', 's3-concept.js', 's4-venn.js',
                's5-practice.js', 's6-sports.js', 's7-summary.js'],
              expectSteps: [4, 3, 4, 3, 4, 3, 5],
            },
          ] },
        ] },
      ],
    },
    {
      id: 'senior', title: '高中',
      books: [
        { id: 'must1', title: '必修第一册', chapters: [
          { id: 'ch04', title: '第4章 指数函数与对数函数', lessons: [
            {
              id: 's4.2',
              title: '4.2 指数函数的图像和性质',
              path: 'courses/senior/must1/ch04/s4.2-exponential-function/',
              status: 'done',
              scenes: ['s1-review.js', 's2-plotting.js', 's3-symmetry.js', 's4-explore.js',
                's5-properties.js', 's6-compare.js', 's7-population.js'],
              expectSteps: [3, 6, 3, 5, 6, 5, 4],
            },
          ] },
        ] },
      ],
    },
  ],
};
